--CREATE FUNCTION STOKARTTIR(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @ADET+26
--END

--SELECT AD,STOK,DBO.STOKARTTIR(STOK) FROM TBLURUN

--CREATE FUNCTION URUNKAREKOK(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @ADET+(SQRT(@ADET)*3)
--END

--SELECT AD,STOK,DBO.URUNKAREKOK(STOK) FROM TBLURUN

--CREATE FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END

--SELECT DBO.KUCUKHARF(AD),STOK FROM TBLURUN

--CREATE FUNCTION KDV(@FIYAT DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @FIYAT*1.18
--END

--SELECT AD,SATISFIYAT,DBO.KDV(SATISFIYAT)AS 'KDV LI HALI' FROM TBLURUN

--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE URUNID=@URID

--SELECT * FROM DBO.URUNBILGI(4)

--NON CLUSTURED INDEX

--CREATE TABLE TABLO1
--(
--ID INT IDENTITY(1,1),
--AD VARCHAR(20)
--)
--DECLARE @SAYAC INT=1
--WHILE @SAYAC<250001
--BEGIN
--INSERT TABLO1
--SELECT 'Kitap' + CAST(@SAYAC AS VARCHAR(20))
--SET @SAYAC=@SAYAC+1
--END

--SELECT COUNT(*) FROM TABLO1

--SELECT * FROM TABLO1 WHERE ID=210387

--SET STATISTICS IO ON
--SET STATISTICS TIME ON

--SELECT * FROM TABLO1 WHERE ID=210387

--CREATE CLUSTERED INDEX TABLOKAYITGETIR
--ON TABLO1(ID)

--SELECT * FROM TABLO1 WHERE ID=210387

