--use DbYeni
--Create Table TBLMUSTERI
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--SOYAD VARCHAR(20),
--SEHIR VARCHAR(15),
--BAKIYE DECIMAL (18,2)
--)

--CREATE TABLE TBLKATEGORI(
--KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20)
--)

--CREATE TABLE TBLURUN(
--URUNID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--ALISFIYAT DECIMAL(18,2),
--SATISFIYAT DECIMAL(18,2),
--STOK SMALLINT,
--DURUM BIT,
--KATEGORI INT
--)

--CREATE TABLE TBLSATIS(
--SATISID INT PRIMARY KEY IDENTITY(1,1),
--MUSTERI INT,
--URUN INT,
--TARIH DATE
--)

--UPDATE TBLSTOK SET TOPLAMURUN=(
--SELECT COUNT(*) FROM TBLURUN)

--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--UPDATE TBLSTOK SET TOPLAMURUN+=1

--UPDATE TBLSTOK SET TOPLAMURUN=(SELECT SUM(STOK) FROM TBLURUN)
--DROP TRIGGER ARTTIR

--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI=STOK FROM inserted
--UPDATE TBLSTOK SET TOPLAMURUN+=@STOKSAYI

--CREATE TRIGGER AZALT
--ON TBLURUN
--AFTER DELETE
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI=STOK FROM DELETED
--UPDATE TBLSTOK SET TOPLAMURUN=TOPLAMURUN-@STOKSAYI

--INSERT INTO TBLURUN (AD,STOK) VALUES ('MIXER',80)

--TRANSACTION -->ROLLBACK , COMMIT

--BEGIN TRANSACTION
--INSERT INTO TBLKATEGORI (AD) VALUES ('TV')
--INSERT INTO TBLKATEGORI (AD) VALUES ('HALI')
--SELECT * FROM TBLKATEGORI
--ROLLBACK

--BEGIN TRANSACTION
--INSERT INTO TBLURUN (AD,STOK) VALUES ('URUN3',10)
--INSERT INTO TBLURUN (AD,STOK) VALUES ('URUN4','B')
--SELECT * FROM TBLURUN
--COMMIT

