--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP='BÝLGÝSAYAR' AND OGRSEHIR='POLONYA'

--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP='BÝLGÝSAYAR' OR OGRSEHIR='POLONYA'

--DECIMAL(x,y) x: Virgülden önce ki basamak sayýsý y: Virgülden sonra ki basamak sayýsý| x y ve kendisinin toplami olmali

--SELECT * FROM TBLNOTLAR

--SELECT (SINAV1+SINAV2+SINAV3) / 3 FROM TBLNOTLAR

--INSERT INTO TBLOGRENCILER (OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('MEHMET','CETIN','ÝSTANBUL')
--SELECT * FROM TBLOGRENCILER

--INSERT INTO TBLNOTLAR (OGRENCI, DERS, SINAV1, SINAV3) VALUES (5,1,54,68)

--DELETE FROM TBLDERSLER WHERE DERSID=3

--UPDATE TBLOGRENCILER SET OGRCINSIYET='KIZ' WHERE OGRID=3

--UPDATE TBLOGRENCILER SET OGRKULUP='TEKSTÝL' WHERE OGRAD='MEHMET'

--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1 + SINAV2 + SINAV3) / 3

--UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA >= 50

--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA < 50

--SELECT Count(*) AS OgrenciSayi from TBLOGRENCILER
--Select Count(*) As ToplamKisi From TBLOGRENCILER WHERE OGRSEHIR='POLONYA'

--Select Sum(Sýnav1),Sum(Sýnav2),Sum(Sýnav3) From TBLNOTLAR
--Select Avg(Sýnav1),Avg(Sýnav2),Avg(Sýnav3) from TBLNOTLAR
--Select Max(Sýnav1),Max(Sýnav2),Max(Sýnav3) from TBLNOTLAR
--Select Min(Sýnav1),Min(Sýnav2),Min(Sýnav3) from TBLNOTLAR

--Select OGRSEHIR,Count(*) AS TOPLAM From TBLOGRENCILER GROUP BY OGRSEHIR
--SELECT OGRCINSIYET,COUNT(*) AS TOPLAM FROM TBLOGRENCILER GROUP BY OGRCINSIYET
--SELECT DURUM,COUNT(*) AS GecenOgrenciSayisi FROM TBLNOTLAR WHERE DURUM=1 GROUP BY DURUM
--SELECT DURUM,COUNT(*) AS KalanOgrenciSayisi FROM TBLNOTLAR WHERE DURUM=0 GROUP BY DURUM
--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA<50
--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1 + SINAV2 + SINAV3) / 3
--INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV2,SINAV3) VALUES (1003,4,54,78,90),(4,5,63,78,23)

--SELECT OGRKULUP,COUNT(*) AS DAGILIMLAR FROM TBLOGRENCILER GROUP BY OGRKULUP
--SELECT MAX(OGRKULUP) AS EnCokOgrenciKulubu FROM TBLOGRENCILER

--SELECT OGRSEHIR,COUNT(*) AS 'SAYI' FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2
--SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP HAVING OGRKULUP='SIBER'
--SELECT DURUM,COUNT(*) AS 'GECENLER' FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM=1
--SELECT DURUM,COUNT(*) AS 'KALANLAR' FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM=0

--use DbOgrenciNot
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE 'G%'
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE '%A'
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE '_____'
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE 'AL%'
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE '%EH%'
--SELECT OGRAD FROM TBLOGRENCILER WHERE OGRAD LIKE 'N____'
--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP NOT LIKE '%a%'

--SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER
--SELECT COUNT(DISTINCT(OGRSEHIR)) AS 'TOPLAMSEHIR' FROM TBLOGRENCILER
--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER
--SELECT COUNT(DISTINCT(OGRKULUP)) AS 'KULUPSAYISI' FROM TBLOGRENCILER

--use DbOgrenciNot
----SELECT * FROM TBLOGRENCILER ORDER BY OGRAD ASC
----SELECT * FROM TBLOGRENCILER ORDER BY OGRSEHIR DESC

----SELECT DISTINCT OGRKULUP,COUNT(OGRKULUP) AS OGRENCISAYISI FROM TBLOGRENCILER GROUP BY OGRKULUP ORDER BY OGRKULUP DESC

----SELECT * FROM TBLOGRENCILER where OGRSEHIR like '%is_%'

----select * from TBLOGRENCILER where OGRAD like '[A,B]%'

--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '[A-M]%'

--SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '[^A]%'

--SELECT TOP 3 * FROM TBLOGRENCILER ORDER BY OGRID desc

--SELECT TOP 60 PERCENT * FROM TBLOGRENCILER

--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR IN('ÝSTANBUL', 'ALMANYA')

--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR NOT IN('ÝSTANBUL', 'ALMANYA')

--SELECT * FROM TBLNOTLAR WHERE ORTALAMA BETWEEN 70 AND 100

--SELECT * FROM TBLOGRENCILER WHERE OGRAD BETWEEN 'A' AND 'N'

--SELECT * FROM TBLOGRENCILER WHERE OGRAD NOT BETWEEN 'A' AND 'C'

--use DbOgrenciNot

--INSERT INTO TBLKULUPLER (KULUPAD) VALUES ('BÝLGÝSAYAR'),('SIBER'),('NÜKLEER'),('TEKSTÝL'),('SATRANC')

--UPDATE TBLOGRENCILER SET OGRKULUP=5 WHERE OGRKULUP='SATRANC'

--INSERT INTO TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('MEHMET',5,'HOLLANDA')

--use DbOgrenciNot
--SELECT NOTID,OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,
--CASE WHEN DURUM=1 THEN 'GECTI' WHEN DURUM=0 THEN 'KALDI' END AS DURUM
--FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.dersid
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID

--UPDATE TBLNOTLAR SET DURUM = CASE WHEN ORTALAMA >= 50 THEN 1 WHEN ORTALAMA < 50 THEN 0 END

--SELECT DERS,SINAV1,SINAV2,SINAV3,ORTALAMA,dersad FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.dersid WHERE DERS=1

--SUB QUERY
--SELECT * FROM TBLNOTLAR WHERE DERS=(SELECT dersid FROM TBLDERSLER WHERE DERSAD='Matematik')

--SELECT * FROM TBLNOTLAR WHERE DERS=(SELECT dersid FROM TBLDERSLER WHERE DERSAD='Satranc') AND 
--SINAV1=(SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS=(SELECT dersid FROM TBLDERSLER WHERE DERSAD='Satranc'))

--use DbOgrenciNot
--SELECT OGRENCI FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI

--SELECT OGRENCI FROM TBLNOTLAR
--LEFT JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI

--SELECT OGRENCI FROM TBLNOTLAR
--RIGHT JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI

--SELECT OGRENCI FROM TBLNOTLAR
--FULL JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI

--SELECT * FROM TBLKULUPLER UNION
--SELECT * FROM TBLDERSLER

--Select 20+4 AS 'TOPLAM', 20-4 'CIKARMA', 20*4 'CARPMA', 20/4 'BOLME'

--SELECT * FROM TBLNOTLAR WHERE DERS=1

--UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1
--SELECT * FROM TBLNOTLAR WHERE DERS=1

--UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100

--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3) / 3

--SELECT AVG(ORTALAMA) FROM TBLNOTLAR WHERE DERS=1

--SELECT OGRENCI,CASE WHEN ORTALAMA>(SELECT AVG(ORTALAMA) FROM TBLNOTLAR) THEN 'GECTI' 
--WHEN ORTALAMA<(SELECT AVG(ORTALAMA) FROM TBLNOTLAR) THEN 'KALDI' 
--END AS DURUM FROM TBLNOTLAR INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID

--SELECT * FROM TBLNOTLAR

--ABS,POWER,SQRT,FLOOR,CEILING,ROUND
--SELECT ABS(-85) AS 'MUTLAK'
--SELECT POWER(2,4) AS 'US ALMA 2 UZERI 4'
--SELECT SQRT(625) AS 'KAREKOK'
--SELECT FLOOR(4.86) AS 'TABANA YUVARLAMA'
--SELECT CEILING(4.86) AS 'TAVANA YUVARLAMA'
--SELECT ROUND(4.4953,2) AS 'YUVARLAMA'

--SELECT SUM(SINAV1+SINAV2+SINAV3) FROM TBLNOTLAR WHERE OGRENCI=1
--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1
--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.dersid 
--WHERE OGRENCI=(SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='ALÝCAN' AND OGRSOYAD='KAYA')

--OGRENCILERDEN AHMET IN SINAV1 DEKI NOTU SATRANC KULUBUNDEKILERIN ORTALAMASINDAN YUKARIDA MI ASAGIDA MI

--SELECT AVG(SINAV1) AS 'GENEL ORTALAMA' FROM TBLNOTLAR

--SELECT(SELECT SINAV1 FROM TBLNOTLAR INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID WHERE OGRAD='AHMET')
--AS 'AhmetSINAV1', AVG(SINAV1) AS 'SATRANC_ORTALAMASI', CASE WHEN (SELECT SINAV1 FROM TBLNOTLAR INNER JOIN TBLOGRENCILER
--ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID WHERE OGRAD = 'AHMET') > AVG(SINAV1) THEN 'USTTE'
--WHEN (SELECT SINAV1 FROM TBLNOTLAR INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
--WHERE OGRAD = 'AHMET') < AVG(SINAV1) THEN 'ALTTA' END AS 'SONUC'
--FROM TBLNOTLAR INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID
--WHERE TBLOGRENCILER.OGRKULUP = (SELECT OGRKULUP FROM TBLOGRENCILER WHERE OGRAD = 'AHMET')

--SELECT UPPER('merhaba') AS 'Sutun'

--SELECT UPPER(OGRAD) AS 'Ogrenci Adlari Buyuk', upper(OGRSOYAD) AS 'Ogrenci Soyadlari Buyuk' FROM TBLOGRENCILER

--SELECT LOWER(OGRAD) AS 'Ogrenci Adlari Kucuk', lower(OGRSOYAD) AS 'Ogrenci Soyadlari Kucuk' FROM TBLOGRENCILER

-- SEHRI Edirne OLAN VE SATRANC KULUBUNDE BULUNAN OGRENCILERIN ADINI BUYUK SOYADINI KUCUK GETIREN SORGU

--SELECT UPPER(OGRAD) AS 'Ogrenci Isim Buyuk Harf', LOWER(OGRSOYAD) AS 'Ogrenci Soyad Kucuk Harf'
--FROM TBLOGRENCILER INNER JOIN TBLKULUPLER ON TBLOGRENCILER.OGRKULUP=TBLKULUPLER.KULUPID
--WHERE OGRSEHIR='EDIRNE' AND TBLOGRENCILER.OGRKULUP in (SELECT KULUPID FROM TBLKULUPLER WHERE KULUPAD='SATRANC')

--SELECT SUBSTRING(OGRAD,1,1) + '.' + OGRSOYAD AS 'AD SOYAD', 
--SUBSTRING(KULUPAD,1,3) as 'KULUP ADI'
--FROM TBLOGRENCILER INNER JOIN TBLKULUPLER
--ON TBLOGRENCILER.OGRKULUP=TBLKULUPLER.KULUPID

--SELECT LEFT('MERHABA DUNYA',9), RIGHT('MERHABA ISTANBUL',2)
--SELECT LEFT(OGRAD,1) + '.' + OGRSOYAD AS 'AD SOYAD' FROM TBLOGRENCILER

--SELECT LEFT(DERSAD,3),AVG(ORTALAMA) FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLDERSLER.dersid=TBLNOTLAR.DERS GROUP BY DERSAD

--SELECT LEFT(DERSAD,3),AVG(LEFT(ORTALAMA,2)*1) FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLDERSLER.dersid=TBLNOTLAR.DERS GROUP BY DERSAD

--SELECT LEFT(OGRAD,2) + REPLICATE('*',LEN(OGRAD) - 2) FROM TBLOGRENCILER

--SELECT LEN('MERHABA')

--SELECT OGRAD,LEN(OGRAD) AS 'ISIM KARAKTER UZUNLUGU',OGRKULUP FROM TBLOGRENCILER
--WHERE OGRSEHIR='EDIRNE' AND OGRKULUP=(SELECT KULUPID FROM TBLKULUPLER WHERE KULUPAD='SATRANC')

--SELECT * FROM TBLOGRENCILER WHERE LEN(OGRAD)=4 OR LEN(OGRAD)=3

--SELECT * FROM TBLOGRENCILER WHERE LEN(OGRAD) + LEN(OGRSOYAD) BETWEEN 3 AND 10

--SELECT Ltrim('          Korkma Sonmez Bu Safaklarda Yuzen Al Sancak') AS 'Istiklal Marsi Ilk Dize'
--SELECT Rtrim('Korkma Sonmez Bu Safaklarda Yuzen Al Sancak          ') AS 'Istiklal Marsi Ilk Dize'

--SELECT REPLACE('Alican Kaya', 'Kaya','K.')

--SELECT REPLACE('Merhaba Bugun Hava Soguk','Hava','Disarisi')
--1.parametre ana kelime veya cumle
--2.parametre bulanacak deger
--3.parametre yeni deger

--Select CHARINDEX('e','SQL Derslerine Devam Ediyorum',15)

--Select LEN('SQL Derslerine Devam Ediyorum')

--Select DATALENGTH('SQL Derslerine Devam Ediyorum')

--SELECT CHARINDEX('a',ograd) from TBLOGRENCILER

--SELECT REVERSE('Alican')

--SELECT REVERSE(Dersad) from TBLDERSLER

--create database SatisVT

--use SatisVT

--create Table TBLKATEGORI
--(
--KATEGORIID tinyint identity(1,1) primary key,
--KATEGORIAD varchar(50)
--)

--create Table TBLURUNLER
--(
--URUNID int identity(1,1) primary key,
--URUNAD varchar(50),
--URUNMARKA varchar(50),
--KATEGORI tinyint,
--URUNALISFIYAT decimal(18,2),
--URUNSATISFIYAT decimal(18,2),
--URUNSTOK smallint check(URUNSTOK>0),
--URUNDURUM bit default '1'
--)

--INSERT INTO TBLURUNLER(urunad) values ('Buzdolabý')

--create Table TBLPERSONEL
--(
--PERSONELID smallint identity(1,1) primary key,
--PERSONELADSOYAD varchar(50)
--)

--create table TBLMUSTERI
--(
--MUSTERIID int primary key identity(1,1),
--MUSTERIAD varchar(50),
--MUSTERISOYAD varchar(50),
--MUSTERISEHIR varchar(13),
--MUSTERIBAKIYE decimal(18,2)
--)

--create table TBLHAREKET
--(
--HAREKETID int primary key identity(1,1),
--URUN int,
--MUSTERI int,
--PERSONEL smallint,
--ADET int,
--TUTAR decimal(18,2),
--TARIH smalldatetime
--)

--TRUNCATE TABLE TBLURUNLER

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')

--INSERT INTO TBLURUNLER(URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK) 
--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)

--select * from TBLURUNLER

--UPDATE TBLURUNLER SET URUNAD='SU ISITICI' WHERE URUNAD='KETTLE'

--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM URUN' FROM TBLURUNLER INNER JOIN TBLKATEGORI 
--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID
--GROUP BY KATEGORIAD ORDER BY COUNT

--KATEGORI ADI BILGISAYAR OLAN URUNLERIN SATIS FIYATINA 500 TL ZAM YAPALIM...

--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 
--WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR')

--SELECT * FROM TBLURUNLER

--TV KATEGORISINDEKI URUNLERIN %10 INDIRIM YAPAN SORGU

--UPDATE TBLURUNLER SET URUNSATISFIYAT=URUNSATISFIYAT - (URUNSATISFIYAT * 0.1)
--WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='TV')

--SELECT COUNT(*) AS 'KAC FARKLI URUN',SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER

--SELECT * FROM TBLURUNLER

--SELECT SUM(URUNSATISFIYAT*URUNSTOK) 'TOPLAM KAZANC' FROM TBLURUNLER WHERE URUNMARKA='SIEMENS'

--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK, 
--(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'
--FROM TBLURUNLER INNER JOIN TBLKATEGORI
--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID

--TOPLAM KARI 1000 TL ALTINDA KALAN URUNLERE SATIS FIYATINA %20 ZAM YAPAN SORGU

--UPDATE TBLURUNLER SET URUNSATISFIYAT=URUNSATISFIYAT+(URUNSATISFIYAT*0.2) 
--WHERE URUNID IN (SELECT URUNID FROM TBLURUNLER WHERE (URUNSATISFIYAT - URUNALISFIYAT)*URUNSTOK < 1000)

--CREATE PROCEDURE HAREKETLER AS
--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD SOYAD',PERSONELADSOYAD,ADET,TUTAR,TARIH
--FROM TBLHAREKET 
--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXEC HAREKETLER

--Create Procedure DENEME
--AS
--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10

--EXEC DENEME

--DROP PROCEDURE DENEME

--ALTER PROCEDURE [dbo].[HAREKETLER] AS
--SELECT HAREKETID,URUNAD,LEFT(MUSTERIAD,1) + '.' + MUSTERISOYAD AS 'AD SOYAD',PERSONELADSOYAD,ADET,TUTAR,TARIH
--FROM TBLHAREKET 
--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXEC HAREKETLER

--ALTER PROCEDURE URUNGETIR
--@Deger varchar(50)='BUZDOLABI'
--AS
--BEGIN
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNAD=@Deger
--END

--EXEC URUNGETIR @Deger='LAPTOP'

--CREATE PROCEDURE STOKSAYISI10
--@Stok INT=10
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNSTOK=10

--EXEC STOKSAYISI10 @Stok=10

--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 16 AND 18 AND MUSTERI=1

--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 15 AND 18 AND 
--MUSTERI=(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')

--SELECT DATENAME(MONTH,getdate()),datename(month,'2025.02.15')

--SELECT DATENAME(DAY,GETDATE())
--SELECT DATENAME(WEEKDAY,GETDATE()) 

--SELECT DATENAME(WEEKDAY,'2025.06.10') TARIH HANGI GUNE DENK GELIYOR

--SELECT DATEDIFF(YEAR,'2024.01.15',GETDATE())
--SELECT DATEDIFF(MONTH,'2024.12.11','2025.01.18')
--SELECT DATEDIFF(DAY,TARIH,GETDATE()) AS 'ILK ISLEM' FROM TBLHAREKET WHERE HAREKETID=1

--SELECT DATEADD(YEAR,3,'2025.01.15')
--SELECT DATEADD(DAY,35,'2025.01.15')
--SELECT DATEADD(MONTH,350,'2025.01.15')

--SELECT * FROM TBLMUSTERI

--SELECT URUNAD,COUNT(*) AS 'SATILAN MIKTAR' 
--FROM TBLHAREKET INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID GROUP BY URUNAD ORDER BY COUNT(*)

--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE KATEGORI=1)

--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE KATEGORI IN 
--(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR'))

--SELECT * FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA')

--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA')

--SELECT MUSTERIAD,MUSTERIBAKIYE FROM TBLMUSTERI WHERE MUSTERIID IN 
--(SELECT MUSTERI FROM TBLHAREKET WHERE URUN=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))

--SELECT SUM(TUTAR) AS 'ANKARA VE ADANALI SATIS' FROM TBLHAREKET 
--WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR IN ('ADANA','ANKARA'))

--SELECT * FROM TBLHAREKET WHERE URUN=1

--UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET
--WHERE URUN=1) WHERE URUNID= 1

--CREATE TABLE TBLKASA
--(
-- TOPLAM decimal(18,2)
--)

--INSERT INTO TBLKASA VALUES (0)
--SELECT * FROM KASA
--UPDATE TBLKASA SET TOPLAM=TOPLAM+(SELECT SUM(TUTAR) FROM TBLHAREKET)

--CREATE TABLE TBLSAYAC
--(
--ISLEM INT
--)

--INSERT INTO TBLSAYAC VALUES(0)

--UPDATE TBLSAYAC SET ISLEM=(SELECT COUNT(*) FROM TBLHAREKET)

--CREATE TRIGGER ISLEMARTIS
--ON TBLHAREKET AFTER INSERT
--AS
--UPDATE TBLSAYAC SET ISLEM=ISLEM+1

--CREATE TABLE TBLTOPLAMKATEGORI
--(
--ADET tinyint
--)

--UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBLKATEGORI)

--CREATE TRIGGER KATEGORIARTIS
--ON TBLKATEGORI AFTER INSERT
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET+=1

--CREATE TRIGGER KATEGORIAZALIS
--ON TBLKATEGORI AFTER DELETE
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET-=1

--CREATE VIEW TEST1
--AS
--SELECT * FROM TBLKATEGORI

--SELECT * FROM TEST1

--ALTER VIEW TEST1
--AS 
--SELECT * FROM TBLKATEGORI WHERE KATEGORIID < 4

--SELECT * FROM TEST2

--SELECT * FROM TEST3

--IF NOT EXISTS (
-- SELECT * FROM sys.tables WHERE name = 'City'
--)
--BEGIN

--CREATE TABLE City (
-- code char(2) NOT NULL,
-- name nvarchar(50) NOT NULL
--)

--INSERT INTO City VALUES
--('01', N'Adana'),
--('02', N'Adýyaman'),
--('03', N'Afyon'),
--('04', N'Aðrý'),
--('05', N'Amasya'),
--('06', N'Ankara'),
--('07', N'Antalya'),
--('08', N'Artvin'),
--('09', N'Aydýn'),
--('10', N'Balýkesir'),
--('11', N'Bilecik'),
--('12', N'Bingöl'),
--('13', N'Bitlis'),
--('14', N'Bolu'),
--('15', N'Burdur'),
--('16', N'Bursa'),
--('17', N'Çanakkale'),
--('18', N'Çankýrý'),
--('19', N'Çorum'),
--('20', N'Denizli'),
--('21', N'Diyarbakýr'),
--('22', N'Edirne'),
--('23', N'Elazýð'),
--('24', N'Erzincan'),
--('25', N'Erzurum'),
--('26', N'Eskiþehir'),
--('27', N'Gaziantep'),
--('28', N'Giresun'),
--('29', N'Gümüþhane'),
--('30', N'Hakkari'),
--('31', N'Hatay'),
--('32', N'Isparta'),
--('33', N'Mersin'),
--('34', N'Ýstanbul'),
--('35', N'Ýzmir'),
--('36', N'Kars'),
--('37', N'Kastamonu'),
--('38', N'Kayseri'),
--('39', N'Kýrklareli'),
--('40', N'Kýrþehir'),
--('41', N'Kocaeli'),
--('42', N'Konya'),
--('43', N'Kütahya'),
--('44', N'Malatya'),
--('45', N'Manisa'),
--('46', N'K.Maraþ'),
--('47', N'Mardin'),
--('48', N'Muðla'),
--('49', N'Muþ'),
--('50', N'Nevþehir'),
--('51', N'Niðde'),
--('52', N'Ordu'),
--('53', N'Rize'),
--('54', N'Sakarya'),
--('55', N'Samsun'),
--('56', N'Siirt'),
--('57', N'Sinop'),
--('58', N'Sivas'),
--('59', N'Tekirdað'),
--('60', N'Tokat'),
--('61', N'Trabzon'),
--('62', N'Tunceli'),
--('63', N'Þanlýurfa'),
--('64', N'Uþak'),
--('65', N'Van'),
--('66', N'Yozgat'),
--('67', N'Zonguldak'),
--('68', N'Aksaray'),
--('69', N'Bayburt'),
--('70', N'Karaman'),
--('71', N'Kýrýkkale'),
--('72', N'Batman'),
--('73', N'Þýrnak'),
--('74', N'Bartýn'),
--('75', N'Ardahan'),
--('76', N'Iðdýr'),
--('77', N'Yalova'),
--('78', N'Karabük'),
--('79', N'Kilis'),
--('80', N'Osmaniye'),
--('81', N'Düzce')

--END

